version: 0.3.2.{build}
image: Visual Studio 2019

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - set PATH=C:\Qt\5.15\msvc2019_64\bin\;C:\Qt\Tools\QtCreator\bin\;%PATH%
  - qmake -v

before_build:
  - mkdir build
  - cd build
  - qmake ..\src\NotepadNext.pro "APP_VERSION=%APPVEYOR_BUILD_VERSION%"

build_script:
  - jom

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - jom zip
  - appveyor PushArtifact NotepadNext.zip -FileName NotepadNext-v%APPVEYOR_BUILD_VERSION%.zip
