version: 0.1.0.{build}
image: Visual Studio 2017

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - set PATH=C:\Qt\5.13\msvc2017_64\bin\;C:\Qt\Tools\QtCreator\bin\;%PATH%
  - qmake -v

before_build:
  - mkdir build_app
  - cd build_app
  - qmake ..\src\NotepadNext.pro

build_script:
  - jom

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - xcopy build_app\NotepadNext\NotepadNext.exe installer\packages\app\data\
  - windeployqt --release --no-translations --no-system-d3d-compiler --no-compiler-runtime --no-angle --no-opengl-sw installer\packages\app\data\NotepadNext.exe
  - 7z a NotepadNext.zip .\installer\packages\app\data\*
  - 7z a installer\packages\app\data\data.7z .\installer\packages\app\data\* -sdel
  - mkdir build_installer
  - cd build_installer
  - qmake ..\installer\installer.pro
  - jom
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor PushArtifact NotepadNext.zip -FileName NotepadNext-v%APPVEYOR_BUILD_VERSION%.zip
  - appveyor PushArtifact build_installer\NotepadNext-v0.1.exe -FileName NotepadNext-v%APPVEYOR_BUILD_VERSION%-setup.exe

deploy:
  provider: GitHub
  auth_token:
    secure: qrw+nu8dQKFLG+lNmky6buHsvHFwlibAai0r0aJ3MYbyBniONVxvgnmyx37bPh44
  artifact: NotepadNext-v$(appveyor_build_version).zip, NotepadNext-v$(appveyor_build_version)-setup.exe
  draft: true
  force_update: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
