name: Build Notepad Next

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
        - 
          qt_version: "5.15.2"
          modules: ""
        - 
          qt_version: "6.2.2"
          modules: "qt5compat"

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          modules: ${{ matrix.modules }}

      - name: Setup VS tools
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install jom
        run: choco install jom

      - name: Run QMake
        run: |
          mkdir build
          cd build
          qmake ..\src\NotepadNext.pro
      
      - name: Build
        run: |
          cd build
          jom

      - name: Create package
        run: |
          cd build
          jom package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: NotepadNext
          path: ${{ github.workspace }}/build/package/
